name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Set up Node.js and cache pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install pnpm globally
      - run: npm install -g pnpm

      # Install dependencies using pnpm
      - run: pnpm install --frozen-lockfile

      # Set SHAs for Nx affected commands
      - uses: nrwl/nx-set-shas@v4

      # Run affected lint, test, and build tasks
      - run: pnpm nx affected -t lint test build
