name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Install pnpm globally first
      - name: Install pnpm
        run: npm install -g pnpm

      # Set up Node.js (don't use cache: 'pnpm' unless pnpm is installed first)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache pnpm store manually (optional but better control)
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies using pnpm
      - run: pnpm install --frozen-lockfile

      # Set SHAs for Nx affected commands
      - uses: nrwl/nx-set-shas@v4

      # Run affected lint, test, and build tasks
      - run: pnpm nx affected -t lint test build
